"""
unittest_final.py

This file contains a lightweight unit test suite for validating the major
components of the CMSE 802 final project. It checks that:

1. The dataset loads correctly.
2. Polynomial regression returns the correct output structure.
3. Gradient Boosting using only Re returns model, metrics, and best parameters.
4. Gradient Boosting using Re and St returns model, metrics, and best parameters.

Only a small sample of the dataset is used to keep execution fast.
"""

import sys
import os
import unittest
import pandas as pd

# Add project root to sys.path so imports work correctly
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, PROJECT_ROOT)

# Import the project modules under test
from src.data_loader import load_data
from src.polynomial_regression import polynomial_regression
from src.gbr_model import train_gbr


class TestCMSE802Project(unittest.TestCase):
    """
    Unit tests for the dataset loader, polynomial regression,
    and Gradient Boosting regression components.
    """

    @classmethod
    def setUpClass(cls):
        """
        Load the dataset once before all tests.
        A subset of 50 rows is used for efficiency.
        """
        df_full = load_data("data/vortex_data.csv")
        cls.df = df_full.head(50)
     # This code snippet is generated by OPEN AI chatgpt version 5.1

    def test_data_loader(self):
        """
        Verify that the dataset loads correctly and contains required columns.
        """
        df = self.df
        self.assertFalse(df.empty, "Dataset should not be empty.")
        self.assertIn("Re", df.columns, "Re column is missing.")
        self.assertIn("St", df.columns, "St column is missing.")
        self.assertIn("Cd", df.columns, "Cd column is missing.")

    def test_polynomial_regression(self):
        """
        Ensure polynomial_regression returns a tuple of:
        (model, polynomial_features_object, metrics_dictionary).
        """
        output = polynomial_regression(self.df)

        self.assertIsInstance(output, tuple, "Output must be a tuple.")
        self.assertEqual(len(output), 3, "Output should contain 3 elements.")

        metrics = output[2]
        self.assertIsInstance(metrics, dict, "Metrics must be a dictionary.")
        self.assertGreater(len(metrics), 0, "Metrics dictionary should not be empty.")

    def test_gbr_re(self):
        """
        Ensure train_gbr using only Re returns:
        (model, metrics_dictionary, best_params_dictionary).
        """
        output = train_gbr(self.df, use_st=False)

        self.assertIsInstance(output, tuple, "Output must be a tuple.")
        self.assertEqual(len(output), 3, "Expected 3 returned values.")

        model, metrics, best_params = output

        expected_metric_keys = [
            "train_r2", "test_r2",
            "train_rmse", "test_rmse",
            "train_mae", "test_mae"
        ]
        for key in expected_metric_keys:
            self.assertIn(key, metrics, f"Missing metric: {key}")

        expected_param_keys = ["n_estimators", "learning_rate", "max_depth", "subsample"]
        for key in expected_param_keys:
            self.assertIn(key, best_params, f"Missing hyperparameter: {key}")

    def test_gbr_re_st(self):
        """
        Ensure train_gbr using Re and St returns:
        (model, metrics_dictionary, best_params_dictionary).
        """
        output = train_gbr(self.df, use_st=True)

        self.assertIsInstance(output, tuple, "Output must be a tuple.")
        self.assertEqual(len(output), 3, "Expected 3 returned values.")

        model, metrics, best_params = output

        expected_metric_keys = [
            "train_r2", "test_r2",
            "train_rmse", "test_rmse",
            "train_mae", "test_mae"
        ]
        for key in expected_metric_keys:
            self.assertIn(key, metrics)

        expected_param_keys = ["n_estimators", "learning_rate", "max_depth", "subsample"]
        for key in expected_param_keys:
            self.assertIn(key, best_params)


if __name__ == "__main__":
    unittest.main()
