"""
eda.py

This file performs exploratory data analysis for the vortex cylinder dataset.

It creates four types of outputs.
1. Summary statistics saved as CSV.
2. Histograms for Re, St and Cd.
3. Pairplot for the three variables.
4. Correlation heatmap.
"""

import os
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


def run_eda(df, save_dir):
    """
    Generate exploratory data analysis plots and summary statistics.

    Parameters
    df : pandas DataFrame
        Dataset containing Re, St and Cd.
    save_dir : str
        Directory where all analysis results will be saved.
    """

    # Create folder if needed
    if not os.path.exists(save_dir):
        os.makedirs(save_dir)

    # 1. Save summary statistics
    df.describe().to_csv(os.path.join(save_dir, "summary_stats.csv"))

    # 2. Histograms for Re, St, Cd
    for col in ["Re", "St", "Cd"]:
        plt.figure(figsize=(6, 4))
        sns.histplot(df[col], kde=True, bins=40)
        plt.title(f"Histogram of {col}")
        plt.tight_layout()
        plt.savefig(os.path.join(save_dir, f"hist_{col}.png"))
        plt.close()

    # 3. Pairplot of variables
    sns.pairplot(df[["Re", "St", "Cd"]], diag_kind="kde")
    plt.savefig(os.path.join(save_dir, "pairplot.png"))
    plt.close()
    # This code snippet is generated by OPEN AI chatgpt version 5.1

    # 4. Correlation heatmap
    plt.figure(figsize=(6, 4))
    sns.heatmap(df[["Re", "St", "Cd"]].corr(), annot=True, cmap="coolwarm")
    plt.title("Correlation Heatmap")
    plt.tight_layout()
    plt.savefig(os.path.join(save_dir, "corr_heatmap.png"))
    plt.close()
