"""
polynomial_regression.py

This file trains polynomial regression models for predicting Cd from Re.

It performs the following tasks.
1. Split the data into train and test.
2. Train polynomial models for degrees from 1 to max degree.
3. Compute metrics for each degree.
4. Select the degree with highest test R2 score.
5. Return the best model, best polynomial transformer and all results.
"""

import numpy as np
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.model_selection import train_test_split


def polynomial_regression(df, max_degree=5):
    """
    Train polynomial regression models of different degrees.

    Parameters
    df : pandas DataFrame
        Dataset with Re and Cd.
    max_degree : int
        Highest polynomial degree to be tested.

    Returns
    best_model : LinearRegression model for best degree
    best_poly_obj : PolynomialFeatures object for best degree
    all_results : dictionary containing metrics for each degree
    """

    # 1. Select input and output variables
    X = df[["Re"]].values
    y = df["Cd"].values

    # 2. Split data into train and test sets
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    results = {}
    best_score = -1
    best_model = None
    best_poly_obj = None

    # 3. Loop through polynomial degrees
    for deg in range(1, max_degree + 1):

        poly = PolynomialFeatures(degree=deg)
        X_train_poly = poly.fit_transform(X_train)
        X_test_poly = poly.transform(X_test)

        model = LinearRegression()
        model.fit(X_train_poly, y_train)
        # This code snippet is generated by Open AI chatgpt version 5.1  

        # 4. Predict train and test outputs
        y_train_pred = model.predict(X_train_poly)
        y_test_pred = model.predict(X_test_poly)

        # 5. Compute metrics for this degree
        train_r2 = r2_score(y_train, y_train_pred)
        test_r2  = r2_score(y_test, y_test_pred)
        train_rmse = np.sqrt(mean_squared_error(y_train, y_train_pred))
        test_rmse  = np.sqrt(mean_squared_error(y_test, y_test_pred))
        train_mae = mean_absolute_error(y_train, y_train_pred)
        test_mae  = mean_absolute_error(y_test, y_test_pred)

        results[deg] = {
            "train_r2": train_r2,
            "test_r2": test_r2,
            "train_rmse": train_rmse,
            "test_rmse": test_rmse,
            "train_mae": train_mae,
            "test_mae": test_mae,
        }

        # 6. Track best model based on test R2
        if test_r2 > best_score:
            best_score = test_r2
            best_model = model
            best_poly_obj = poly

    return best_model, best_poly_obj, results


